### ISSUE TITLE
MyReceiver.class找不到的问题

### ISSUE THREAD

**Issue by LINHANKK** [RebelliousVicuna/LCU_Library#3]

**Comment by LINHANKK** [comment]
请问在MyService中为什么找不到MyReceiver类呢

**Comment by RebelliousVicuna** [comment]
github代码部分有删减，那个类可能我删了🙃

**Comment by RebelliousVicuna** [comment]
> 请问在MyService中为什么找不到MyReceiver类呢

代码有部分删减，可能那个类我给删了🙃

**Comment by LINHANKK** [comment]
那请问这个地方应该怎么解决呢

**Comment by RebelliousVicuna** [comment]
> 那请问这个地方应该怎么解决呢
莫得办法。

如果是参考怎么写的话，那个类可有可无，你自己写一个差不多的也行。
如果要是让源码运行起来，那个类算是比较重要的吧。
不过这个仓库本来就仅供参考🤺🤺

**Comment by LINHANKK** [comment]
好的谢谢
